version: '3'

services:
  feeds:
    image: podcast
    build: ./dockerfiles/servicos/
    hostname: feeds
    # expose: 
    #   - '5000'
    volumes:
      - './feeds:/servico'
    command: python3 -u servico.py
    ports:
      - "5000:5000"
    # networks:
    #    pod:
    #     ipv4_address: 172.29.1.1

  bancodados:
      image: mysql
      hostname: bancodados
      # expose:
      #   - '3306'
      environment:
        MYSQL_ROOT_PASSWORD: admin
      ports:
        - "3306:3306"
      cap_add:
        - SYS_NICE  # CAP_SYS_NICE
      # networks:
      #   pod:
      #     ipv4_address: 172.29.1.5

  arquivos:
    image: arquivos
    build: ./dockerfiles/nginx/
    volumes:  
      - './assets/img:/usr/share/nginx/html/'
    hostname: arquivos
    # expose:
    #   - '80'
    ports:
      - "80:80"
    # networks:
    #    pod:
    #     ipv4_address: 172.29.0.6 

# networks:
#   pod:
#     ipam:
#       driver: default
#       config:
#         - subnet: 172.29.1.0/16

