version: '3'

services:
  feeds:
    image: podcast
    build: ./dockerfiles/servicos/
    hostname: feeds
    volumes:
      - './feeds:/servico'
    command: python3 -u servico.py
    ports:
      - "5000:5000"
  bancodados:
      image: mysql
      hostname: bancodados
      environment:
        MYSQL_ROOT_PASSWORD: admin
      ports:
        - "3306:3306"
      cap_add:
        - SYS_NICE  # CAP_SYS_NICE
  arquivos:
    image: arquivos
    build: ./dockerfiles/nginx/
    volumes:  
      - './assets/img:/usr/share/nginx/html/'
    hostname: arquivos
    ports:
      - "80:80"


